### ISSUE TITLE
 Clarification about the license

### ISSUE THREAD

**Issue by geonux** [Viglino/ol3-ext#1]
Your work on OpenLayers is impressive and we would be very happy to use it. But, as is, nobody can do it because the license of your work is uncertain. It should be clarified.

On one hand the license file (license.txt) announces a license (CeCILL-B) but it contains links to different licenses (CeCILL-B and CeCILL-C):
> Full text license in English: http://www.cecill.info/ licences/Licence_CeCILL-**B**_V1-en.txt
> Full text license in French: http://www.cecill.info/ licences/Licence_CeCILL-**C**_V1-fr.txt

On other hand, the source file headers refer to two different licenses (CeCILL and CeCILL-B). For example:
In control/layerswitchercontrol.js:
> released under the CeCILL-**B** license

In control/piratecontrol.js:
> released under the CeCILL license

These three licenses are noticeably different:
-     The CeCILL license is a "strong copyleft" license. It extends to any derivated work and any component linked against your work. This license is similar to GNU GPL v2 license.
-     The CeCILL-C license is a "weak copyleft" license. It extends to any derivated work but not to components linked against your work. This license is similar to GNU LGPL v2.1 or EPL licenses.
-     The CeCILL-B license is a "permissive" license. It applies on original work but neither to derivated works nor components linked against yout work. This license is similar to BSD, MIT or Apache licenses.

Could you confirm that your work is actually released under the CeCILL-B license as stated in the license file. If applicable, could you adjust the links and the headers?

This would be welcome!

**Comment by Viglino** [comment]
YES! the licence is a BSD compatible licence.
I'll change the header to conform this!
The whole project is under CeCILL-B license as describe in http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

**Comment by geonux** [comment]
Perfect! Waiting for code updating.

**Comment by geonux** [comment]
Thank you for the clarification. Closing the issue.
