### ISSUE TITLE
Animated popup click again on the same point

### ISSUE THREAD

**Issue by kostala** [Viglino/ol3-ext#11]
Hello! 
The "Animated popup!" if you close popup window and click again on the same point, then it is not popup. How to fix?

**Comment by Viglino** [comment]
Hello,
The popup is opened when a feature is selected. If you close the popup the feature is not deselected an clicking again don't do anything. 
To fix this you have to deselect the feature on close. 
Use the onclose callback to do that : 
```javascript
var popup = new ol.Overlay.Popup ({
    onclose: function()
    {    select.getFeatures().clear();
    },
    ... 
});
```

@+
