### ISSUE TITLE
Control bar position

### ISSUE THREAD

**Issue by dmcritchie** [Viglino/ol3-ext#12]
Sorry to bother you again about the control bar, Jean-Marc. I know you support several positions for the control bar, but I'm having problems finding a position that works well for my case. When the control bar(s) are top center, they impinge on the square work area. Putting them on the top-right position is better, but still takes up more real estate than they should because the control bar is vertical but the sub control bar is horizontal. See the attached screen shots. I'm constrained regarding the screen size and layout, so I'm hoping I can move the control bars instead.

![controlbartop](https://cloud.githubusercontent.com/assets/1919285/20322549/cab08a26-ab36-11e6-91de-38d965d320a6.JPG)
![controlbartopright](https://cloud.githubusercontent.com/assets/1919285/20322562/ce2c4474-ab36-11e6-877e-f87b792d3e41.JPG)

Is there any simple way for me to do one of the following:
1) Move the top-center control bar to the right edge of the screen with bar and subbar both horizontal, or
2) Keep the top-right bar vertical but also make the subbar vertical.

I realize you may not want to support these cases in your released code, but if you could point me in the right direction to make one of these two changes, I would appreciate it. Your controlbar and togglecontrol code has been extremely helpful to me thus far.

Thanks,
Dennis

**Comment by Viglino** [comment]
Hi Dennis,
As the layout depend on the application you can set it in the css. The control defines the main position (top/left/bottom/right) but you have to override the position of the bar to place it at the right place. 

If you want it top-right:
```CSS
.ol-control.ol-bar
{  left: auto;
   right: 3em;
   transform: none;
}
```

If you want to have a vertical subbar:
```CSS
.ol-control.ol-bar .ol-option-bar .ol-control
{  display: block;
}
```
@+

**Comment by dmcritchie** [comment]
Thanks Jean-Marc!

That was very helpful.

Best,
Dennis
