### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by craigsnyders** [Viglino/ol3-ext#14]
So that we can use `npm install ol3-ext` or `yarn add ol3-ext`.

Currently I use `yarn add https://github.com/Viglino/ol3-ext#gh-page` but my project might break if there's a breaking change or conflict with my code, because there are no releases (version numbers - https://github.com/Viglino/ol3-ext/issues/13).

**Comment by craigsnyders** [comment]
It seems as though `yarn` is smart enough to use commit versions so that my builds are properly reproducible. From my yarn.lock: 
`resolved "https://github.com/Viglino/ol3-ext#697bb800523a5cc83c0bf0c238d49626a6785bf1"`

That being said, NPM publishing is still desirable to make this awesome library easier to use in many situations

**Comment by Viglino** [comment]
Great!

**Comment by MerlinDuChaos** [comment]
@Viglino , do you plan to publish this to NPM ?  As said by @craigsnyders it would be a great way to import it in project.  Thanks !

**Comment by Viglino** [comment]
Not yet...
Perhaps I'll try to do something for Christmas :-)

**Comment by spongessuck** [comment]
I've published this to npm under the package name `ol3-ext`. Let me know if you want me to transfer ownership of the package to you.

I've published both your `v1.0.1` release and the current state of your `gh-pages` branch, which I've called `v1.0.2-alpha.0`.

**Comment by Viglino** [comment]
Great!
I've planned to do it but I never had time to do it.
The main problem is not to create it, but also to manage versions (people expect stable versions on npm).
Anyway, I think this is a tool expected by some.
Do not hesitate if you want me to run a new version or find bugs on a version.

**Comment by Viglino** [comment]
ol3-ext change is name and is now available on npm: https://www.npmjs.com/package/ol-ext
