### ISSUE TITLE
ol.style.Icon does not allow for source to be SVG

### ISSUE THREAD

**Issue by glchua2** [Viglino/ol3-ext#15]
If src of ol.style.Icon is a SVG, the following error will occur "Uncaught TypeError: Cannot read property '0' of null".

**Comment by Viglino** [comment]
Hello,

`ol.style.Icon` is part of the [ol3 project](https://github.com/openlayers/ol3).
If you have questions about it, please refer to the [StackOverflow forum](http://stackoverflow.com/questions/29152405/how-can-i-use-an-svg-image-as-a-map-marker-in-openlayers-3).
You can find a working example here: http://jsfiddle.net/jonataswalker/yuy85afm/

regards
