### ISSUE TITLE
forEachFeatureAtPixel parameters changed

### ISSUE THREAD

**Issue by zZzimi** [Viglino/ol3-ext#22]
OL's forEachFeatureAtPixel functions parameters have changed in ol v3.20. The Transform interaction use it in the 193 row. There are problem with the scope. You should change the 217 row from `}, this) || {};` to `}.bind(this)) || {};`. Here is the ol's release note: https://github.com/openlayers/openlayers/releases/tag/v3.20.0

**Comment by Viglino** [comment]
You're right :-(

**Comment by Viglino** [comment]
Done in last commit.
