### ISSUE TITLE
ol.control.Bar.setMap(map) : error when map is null

### ISSUE THREAD

**Issue by nicolo73** [Viglino/ol3-ext#23]
Hi,
I'm using ol-ext, it is a awesome library :)

But I have an issue : Null map is not managed in ol.control.Bar.setMap(map)
=> map.addControl(c); is called for sub-controls (buttons)

Note that setMap(null) is called automatically by ol3 when we call map.removeControl(myToolBar)
So this case should be managed in the toolbar code.

Could be fixed calling c.setMap(map) instead of map.addControl(c). 
But setMap(null) should be also managed on other Control as Toggle and Button.

In the same idea, setMap could be used to change Map, it should be better to unregister from old Map if any (remove interaction)...

Good luck, 
Nicolas

**Comment by Viglino** [comment]
You're right, the controls have not been foreseen to be removed from the map... as I don't have to do so (bars are created for a map).
I'll try to do something for that in the next commit to handle such a case.
regards

**Comment by nicolo73** [comment]
Yes indeed, it is probably not usual to remove toolbars... Anyway, I think it would be good to plan this case. Meanwhile I modified the code temporary on a local copy of your library with a simple "if map != null" before calling map.addControl(c)

**Comment by Viglino** [comment]
Done in the last commit.
Now you can add and remove bars and toggle controls to a map.

**Comment by nicolo73** [comment]
Great, Thanks !
