### ISSUE TITLE
Loading content after the opening animated popup

### ISSUE THREAD

**Issue by kostala** [Viglino/ol3-ext#24]
Hello!
How to loading content from the database after the opening animated popup?
That is,
1) make a request to the database, show a blank popup
3) load content

**Comment by Viglino** [comment]
Hello,

On load just redraw the popup with the loaded content:
```javascript
popup.show (position, "loading...");
request = $.ajax({ 
    url: request_url, 
    success: function (content) { popup.show(null, content); } 
});
```
You can use `null` as position to use the current one.

Beware of side effect if more than one request is done (multiple click), as they are asynchronous, the first one may be cached after the second and display a bad content...
Use `request.abort()` before sending another.

@+
