### ISSUE TITLE
Error when using compiled ol3-ext.js

### ISSUE THREAD

**Issue by thhomas** [Viglino/ol3-ext#27]
I have an error when using compiled ol3-ext.js file. 

> Uncaught ReferenceError: map is not defined

on lines : 
`
/** Export PNG / JPEG */
$(document).ready(function()
{	$("a[download]").exportMap(map);
});
`

**Comment by Viglino** [comment]
OK. The line is not at the right place. It should be in the example file and not in the lib  :confused:
I'll remove it in the next commit.
Thanks for the feedback.

**Comment by Viglino** [comment]
Done in the last  commit.
