### ISSUE TITLE
How to rotate labels with ol.interaction.Transform?

### ISSUE THREAD

**Issue by joaorodr84** [Viglino/ol3-ext#28]
Hi, I love your "ol.interaction.Transform". :)

I was wondering if you could add a way to rotate the label of a feature, along with the whole feature.

In this [CodePen](http://codepen.io/joaorodr84/pen/ygqzdP), I prepared an example, where I set the style of a feature, so that it has a text label.

How could we rotate the label?

Thanks a lot! :D

**Comment by Viglino** [comment]
Hello,

Text rotation can be handled using a dynamic style as it is done with the symbol rotation in the example.
Here is an example: http://codepen.io/viglino/pen/LxJQdr

i.e. you can not define the feature style with setStyle. Rather use a style function to define the layer style. It will use feature attributes to draw it (getStyle function l.24 + layer definition l.49).
Then you just have to change the angle attribute of the object in the 'rotating' listener (l.104) to tell the style to rotate the feature.

@+

**Comment by joaorodr84** [comment]
Thank you! :)
