### ISSUE TITLE
Maki-Fonts filling in gaps

### ISSUE THREAD

**Issue by tannerjt** [Viglino/ol3-ext#3]
I can't tell if the maki fonts are filling in their gaps with the same fill color, or maybe not respecting stroke for the FontSymbol.  Icons like 'campsites' appear to be triangles because all the 'empty space' is filled.  Do you think this might be due to the fonticon itself, or something in FontSymbol?

**Comment by Viglino** [comment]
Hy,
I don't notice this. For me the maki fonts are correct and 'campsites' are not filled.
![screenshot](https://cloud.githubusercontent.com/assets/7868217/17084317/ce0e8eb4-51ba-11e6-9419-a3fef2abbb2d.jpg)
The stroke may fill the the gaps if they are too wide.

**Comment by tannerjt** [comment]
Interesting, I wonder if it has to do with how my browser interprets the font.  I tried on FF, Safari, and Chrome.  Here it is in the font list:

![screen shot 2016-07-24 at 12 32 48 pm](https://cloud.githubusercontent.com/assets/3883995/17085981/fe657002-519a-11e6-935d-25002d8ff555.png)

**Comment by Viglino** [comment]
The font used depends on your system/browser
- eot for Internet Explorers older than IE9
- ttf and otf old fonts format
- svg fonts for iOS on iPhone and iPad 
- woff with 
Perhaps one is not generated correctly...
You can try to remove the font definition in the CCS and leave just one format to test ?
Suppose you don't have the same problem with other fonts (FontAwesome).

**Comment by tannerjt** [comment]
You are correct, the woff was the issue and FontAwesome was not experiencing the same problem.  Removing the woff solved the issue.  Thanks!
