### ISSUE TITLE
How to setActive transforminteraction by default

### ISSUE THREAD

**Issue by AntoniBCN** [Viglino/ol3-ext#34]
Hello,

Hi I would have enabled (turned on) the transforminteraction control by default and thus, user does not need to click over the feature to see transformation icons.

Is this possible?

the code bellow does not work:

		var interaction = new ol.interaction.Transform (
			{	
				translateFeature: false,
				scale: true,
				rotate: false,
				keepAspectRatio: undefined,
				translate: true,
				stretch: true,
				source: source,
			});
		interaction.setActive(true);
		map.addInteraction(interaction);

Thanks in advance.

**Comment by Viglino** [comment]
Hello,

The select method of the transform interaction will do that.
You just have to pass the feature you want to transform:
````
var f = source.getFeatures()[0];
interaction.select(f);
````
@+

**Comment by AntoniBCN** [comment]
Great !! Thanks a lot.
