### ISSUE TITLE
Update box (control) using code, not drawing over map

### ISSUE THREAD

**Issue by AntoniBCN** [Viglino/ol3-ext#36]
Hello again,

I need to update the feature box using code. There is a way to pass new bbox coordinates (calculated by external function) to the feature and redraw it?

Thank's in advance.

**Comment by Viglino** [comment]
Hello,
The feature bbox is calculating according its coordinates and can not been modify.

**Comment by AntoniBCN** [comment]
Ok. Thank you anyway. 

Set new coordinates programatically it could be very interesting for a future.
