### ISSUE TITLE
changing Canvas size

### ISSUE THREAD

**Issue by beckerIGG** [Viglino/ol3-ext#37]
Hi,

i am using the animated cluster in conjunction with pie charts. Now i would like to add the size of the pies or bars to the canvas object. However sometimes the size is not displayed due to its position out of the canvas object. How do i change this or are able to display the size over or under the bar for example? I found a solution for displaying it into the pies however inside the elements and not outside, due to the size of the canvas.

BR Thomas

**Comment by Viglino** [comment]
Hi,
I'm not sure what you want to do.
But I think you can use a _ol.style.Text_ to display the size as a text whatever the image symbol is (chart or circle).

**Comment by beckerIGG** [comment]
![pie_chart_with_specific_size](https://cloud.githubusercontent.com/assets/7497356/25846070/b99aca54-34b0-11e7-94b6-187e9936b5c8.jpg)
![bar_chart_with_specific_size](https://cloud.githubusercontent.com/assets/7497356/25846073/bc22bc96-34b0-11e7-9224-9992d49afc97.jpg)

as you can see, i am able to add the size of the cluster elements. However some are not displayed due to the canvas size. Specifically if you have a look on the black column. The size number should be 5px over the column. Any ideas how to achieve this?

**Comment by Viglino** [comment]
The issue of drawing stats values as a symbol is quite difficult because you have to calculate the size of the text to be drawn to fit the symbol and it will depends on the number of digit...
I think the best way is to use an array of style with text ([ol.style.Text](http://openlayers.org/en/latest/apidoc/ol.style.Text.html)) and an offsetX, offsetY and a textAlign, thus the values will be drawn as Text.
You have to calculate the offsetX/offsetY and the alignment according the angle when creating the symbol.

**Comment by Viglino** [comment]
Here is an example to show how : https://jsfiddle.net/Viglino/tw5pd97k/

**Comment by beckerIGG** [comment]
Hi,

thx for this nice example. However i am not able to bring this to work, since i am using the chart style in conjunction with the animated cluster. This means the chart is the the style for the cluster and i have to find a way to integrate the text style into it. If i use your example i get an openlayers errror stating Uncaught TypeError: c.Z is not a function.
thx Thomas

**Comment by Viglino** [comment]
You can use the same techniques with a cluster to calculate the feature style.
Do you have an jsfiddle?

**Comment by beckerIGG** [comment]
Hi,

thx a lot. Found my mistake. Now everything works perfect.
BR Thomas
