### ISSUE TITLE
Make ol.control.Toggle disabled/enabled

### ISSUE THREAD

**Issue by AlenKelemen** [Viglino/ol3-ext#39]
Proposed code to make ol.control.Toggle disabled/enabled:
(insert in ol.control.Toggle code)

* @param {Object=} opt_options Control options.
*		disabled {bool} the control is created disabled, default false
 *		getDisabled() {bool} is control disabled
 *		setDisabled() {bool} disable or enable control
 */

this.setDisabled = function (disabled) {
	        $(this.element).find("button").prop('disabled', disabled);
	        $(this.element).removeClass("ol-active");
	        if (this.interaction_) { this.interaction_.setActive(false) };
	}
	this.setDisabled(options.disabled);
	this.getDisabled = function () {
	    return $(this.element).find("button").prop('disabled')
	};

**Comment by Viglino** [comment]
Good idea. added in the last commit!
