### ISSUE TITLE
Popup close button should specify "type='button'

### ISSUE THREAD

**Issue by pjmeier** [Viglino/ol3-ext#40]
My page was reloading when the close button was clicked on the popups. Tracked it down to the button submitting the page. By default a plain <button> is a submit button by default. Adding "type='button'" changes it to a normal button.

   this.onshow = options.onshow;
    $("<button **type='button'**>").addClass("closeBox").addClass(options.closeBox ? "hasclosebox" : "")

It doesn't seem a problem when using the **select.getFeatures().on(['add'], function(...** event but I was using **map.on('click',..** event. Using this event, the close button was submitting.
To be on the safe side, it's probably good to add the **type=button** to the button.

Thanks for the examples. They've been a great resource.

**Comment by Viglino** [comment]
You're right, I should specify the type attribute. Different browsers may use different default types for the `<button>` element.

**Comment by Viglino** [comment]
Add type="button" on closebox
