### ISSUE TITLE
popupoverlay not displaying first time after page has loaded

### ISSUE THREAD

**Issue by AlenKelemen** [Viglino/ol3-ext#43]
Solution could be to wrap jquery load in $(document).ready.

`$(document).ready(function () {
	        $("*", this.content).load(function () {
	            map.renderSync();
	        })
	    });`

**Comment by Viglino** [comment]
Do you have an example for the issue?

**Comment by AlenKelemen** [comment]
` map.on("singleclick", function (e) {
            var coordinates = map.getCoordinateFromPixel(e.pixel);
            map.popup.show(coordinates, "I am not the first click...");
        });
        map.popup = new ol.Overlay.Popup(
                  {
                      positioning: 'auto'
                  });
        map.addOverlay(map.popup);`

**Comment by Viglino** [comment]
It seems you're using a jQuery version higher than mine. I've change the way to handle popup. Can you see if it solves the issue?
