### ISSUE TITLE
popup error: a.indexOf is not a function

### ISSUE THREAD

**Issue by behzadba** [Viglino/ol3-ext#44]
This error happens on the first run of popup:

```
jquery-3.1.1.min.js:4 Uncaught TypeError: a.indexOf is not a function
    at r.fn.init.r.fn.load (jquery-3.1.1.min.js:4)
    at ol.Overlay.Popup.show (ol3-ext.js:10580)
```

**Comment by behzadba** [comment]
solution was changing load to 'on' at line 10580, so:
`$("*", this.content).on(function()...`

**Comment by AlenKelemen** [comment]
This is the same issue as mine: popupoverlay not displaying first time after page has loaded #43

**Comment by Viglino** [comment]
OK.
It seems you're using a jQuery version higher than mine. I've change the way to handle popups. Can you see if it solves the issue?

**Comment by aliciahogue** [comment]
I had this issue before and would always manually update the code after updating, but resolved now with latest changes.
