### ISSUE TITLE
Is there any plan to enhance Cloud in Map plugin

### ISSUE THREAD

**Issue by alex2wong** [Viglino/ol3-ext#48]
Thanks for providing us so many awesome extensions in ol3. 

I am interested in Cloud plugin. Clouds does not flow with the map view change, namely the cloud is not located in real geolocation, but render as absolute position in canvas. 

I suppose it will be good if you enhance cloud position, with lnglat2pixel like function to make cloud flow in  its geolocation. It would be much more like the real cloud.

Thanks! 
Alex

**Comment by Viglino** [comment]
Clouds are not intended to be used as real clouds...
They have no locations and they are not stored when the goes outside the map (a new one is added on the other side). It is not a very efficient way to do this.
It's just a control that adds an effect on the map...

If you're interested in adding located animated objects on the maps, have a look at the [OL3-games project](https://github.com/Viglino/ol3-games).

**Comment by alex2wong** [comment]
ok, thanks : )
