### ISSUE TITLE
LayerSwitcherControl error

### ISSUE THREAD

**Issue by joseahr** [Viglino/ol3-ext#5]
I have an error with LayerSwitcher when adding the control to map.
The lines of code producing the error (`this.map is undefined`):

```
if (this.map_){	
    this.map_.getLayerGroup().un('change', this.drawPanel, this);
    this.map_.un('moveend', this.viewChange, this);
    this.map.un('change:size', this.overflow, this);  -->> This line
    // console.log("remove");
}
```

solved replacing `this.map.un(...)` to `this.map_.un(...)`

**Comment by Viglino** [comment]
Thanks for the feedback.
I've changed it in the last commit.
