### ISSUE TITLE
will any plan to update ol to v4.x?

### ISSUE THREAD

**Issue by dyh333** [Viglino/ol3-ext#50]
hi, @Viglino . i am learning this repo and like it very much! 
will any plan to update ol to v4.x? 
and about the charts show on map, if can support 3rd library such as highlight, amcharts would be better.

thanks your great job.

**Comment by Viglino** [comment]
Hi,

The library is running on the last release of Openlayers (yet v4.3.0) and follows the commits. If not it's a bug that will be solved asap :smile:

The charts are intended to be used as symbols on the map, not to replace statistical library that can be used to display more information, on a popup for example.

@+
