### ISSUE TITLE
How to change projection of ol.Overlay.Magnify?

### ISSUE THREAD

**Issue by icemagno** [Viglino/ol3-ext#51]
Hi. I'm from Brazil and using EPSG 4326.

			myView = new ol.View({
				center: MCLM.Map.arrayMapCenter,
				zoom: MCLM.Map.mapZoom,
			    minZoom: 2,
			    maxZoom: 19,
			    // projection: 'EPSG:4326',  <<---- Commenting this makes work fine.
			});	

This is causing distortion on lens position:

![lens-error](https://user-images.githubusercontent.com/4127512/30649209-1407e95a-9df6-11e7-8328-ca0c2e92500f.png)

When I comment the projection on my view, the lens works fine, but mess with my map. I need the EPSG:4326.

Would be nice if:

			var layers2 = [	new ol.layer.Tile({	source: new ol.source.OSM()	}) ];			
			var ov = new ol.Overlay.Magnify({	
				layers: layers2,
				zoomOffset: 1,
				projection: 'EPSG:4326'  <<<<<<----- This would be nice !!!!
			});
			map.addOverlay( ov );	

How to make ol.Overlay.Magnify respect my map projection?

**Comment by icemagno** [comment]
Solved by myself.
Add this if yo want:

In ol3-ext.js line 10433:

```
// Create magnify map
this.mgmap_ = new ol.Map(
{	controls: new ol.Collection(),
	interactions: new ol.Collection(),
	target: options.target || this.element,
	view: new ol.View( {projection: options.projection} ),  // ADD THIS OPTION HERE
	layers: options.layers
});
```

And create the Overlay this way:

```
var layers2 = [	new ol.layer.Tile({	source: new ol.source.OSM()	}) ];			
var ov = new ol.Overlay.Magnify({	
	layers: layers2,
	zoomOffset: 1,
	projection: 'EPSG:4326'  //  SET PROJECTION HERE
});
MCLM.Map.map.addOverlay( ov );	
```


All is fine now. Thanks.

**Comment by Viglino** [comment]
Yes! you have to specify the projection of the overlay in the constructor...
I'll see if I can set it when the overlay is added on a map using the map projection.
:wink:
