### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by realjoker** [Viglino/ol3-ext#53]
First of all, awesome job!! I really love the work done here.

The question is: is there any documentation about the extensions?

**Comment by Viglino** [comment]
The documentation is in the code + example. I try to list all functionalities in the examples.
I've tried to use JSDoc to generate it but it is still quite not clear.

**Comment by pitommasi** [comment]
Hi, I see that indeed the examples are well documented and managed so far to get things working.

**Comment by Viglino** [comment]
Hi, I've put an only doc in the project: http://viglino.github.io/ol3-ext/doc/doc-pages/
