### ISSUE TITLE
Geo bookmarks control data file when using more than one openlayer page on same website

### ISSUE THREAD

**Issue by swapps** [Viglino/ol3-ext#54]
Hi,
your Geo bookmarks control is just great !
But i have an issue, i'm hosting more than one openlayer zoomify page on my website. But when i set a bookmark for any of them it is used for the others too.
How can i do to to fix this ?

http://www.preiss.fr/album/giga/

**Comment by Viglino** [comment]
Hi,
Booksmarks are saved in the LocalStorage an thus available for all of maps the site.
The solution would be to add a namespace for each map.
I'll see what can be done.
@+

**Comment by Viglino** [comment]
I've added a namespace parameter to handle differents bookmarks
