### ISSUE TITLE
Split tolerance 

### ISSUE THREAD

**Issue by zZzimi** [Viglino/ol3-ext#56]
Hi,

I'm not sure, but I think at ol.geom.utils.js, 69th row you should change from var ri = result[k].splitAt(pt[i]); to var ri = result[k].splitAt(pt[i], tol); . If I dont use the default tolerance, then it will not use my own tolerance. Am I right? Thanks!

**Comment by Viglino** [comment]
Yes, your right, the tol parameter is missing...
