### ISSUE TITLE
too much recursion in layerswitcher.js

### ISSUE THREAD

**Issue by ebardiere** [Viglino/ol3-ext#57]
If baseLayers have a noSwitcherDelete properties to true, removing all layers create too much recursion in attempting to remove parent layer.
proposition (line 508 layersitcher.js) : 
			if (li.data("layer").getLayers().getLength()==0)
			{
				if (! li.data("layer").get("noSwitcherDelete")) removeLayer.call($(".layerTrash", li), e);
			}
Best regards, Emmanuel (Suisse)

**Comment by Viglino** [comment]
You're right! Thanks for the feedback! 👍
