### ISSUE TITLE
How to use with angular 2+?

### ISSUE THREAD

**Issue by shenchaoran** [Viglino/ol3-ext#59]

**Comment by Viglino** [comment]
The same way you use ol (or any js library) with Angular 2. It's just an ol extension.
Just add it in your` .angular.cli.json` with the related libraries:
```
"scripts":[
        "../node_modules/jquery/dist/jquery.min.js",
        "assets/openlayers/ol.js",
        "assets/ol-ext/ol3-ext.min.js",
]
```
The you can access the lib in your `.ts` files 
```
declare var ol: any;
```

**Comment by shenchaoran** [comment]
Thanks
